core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from core.settings import ENVIRONMENT, MEDIA_ROOT, STATIC_ROOT
from src.core.handlers import (
    handler404, handler500
)

urlpatterns = []

""" HANDLERS ------------------------------------------------------------------------------------------------------- """
handler404 = handler404
handler500 = handler500

""" INTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('', include('src.web.urls')),
    path('', include('src.services.events.urls', namespace='events')),
    path('', include('src.services.departments.urls', namespace='departments')),
    path('', include('src.services.attractions.urls', namespace='attractions')),
    path('', include('src.services.dine_stay.urls', namespace='dine_stay')),
    path('', include('src.services.management.urls', namespace='management')),
    path('', include('src.services.forest.urls', namespace='forest')),
    path('', include('src.services.feedback.urls')),
    
    
]

""" EXTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/services/dine_stay/urls.py
from django.urls import path
from .views import AccommodationListView, AccommodationDetailView, DiningListView, DiningDetailView

app_name = 'diny_stay'
urlpatterns = [
    path('accommodations/', AccommodationListView.as_view(), name='accommodations'),
    path('accommodation/detail/<str:pk>/', AccommodationDetailView.as_view(), name='accommodation-detail'),
    path('dinings/', DiningListView.as_view(), name='dinings'),
    path('dinings/<str:pk>/', DiningDetailView.as_view(), name='dining_detail'),

]

src/services/events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView

app_name = 'events'
urlpatterns = [
    path('event/list/', EventListView.as_view(), name='event_list'),
    path('event/<str:slug>/detail', EventDetailView.as_view(), name='event_detail')
]

src/services/forest/urls.py
from django.urls import path
from .views import (
    WildlifeListView, WildlifeDetailView, WildlifeTypeListView,
    GreeneryListView, GreeneryDetailView, GreeneryTypeListView
)

app_name = 'forest'

urlpatterns = [
    # Wildlife URL patterns
    path('wildlife/types/', WildlifeTypeListView.as_view(), name='wildlife_type'),
    path('wildlife/list/<slug:slug>/', WildlifeListView.as_view(), name='wildlife_list'),
    path('wildlife/detail/<slug:slug>/', WildlifeDetailView.as_view(), name='wildlife_detail'),
    
    # Greenery URL patterns
    path('greenery/types/', GreeneryTypeListView.as_view(), name='greenery_type'),
    path('greenery/list/<slug:slug>/', GreeneryListView.as_view(), name='greenery_list'),
    path('greenery/detail/<slug:slug>/', GreeneryDetailView.as_view(), name='greenery_detail'),
]

src/services/management/urls.py
from django.urls import path

from src.services.management.views import DocumentListView

app_name = 'management'
urlpatterns = [
    path('dowmload/', DocumentListView.as_view(), name='document-list'),
]

src/web/website/urls.py
from django.views.generic import TemplateView

from .views import (

    NewsLetterCreateView,
    about, budget,
    teamDetails,
    act, department, departmentDetails,
    hotels, hotelsDetails, cafedetail,
    cafe, tenders,
    watertax,
    conservancytax,
    boqs, emergencyContact, jurisdiction, ContactView,
    watertax,
    conservancytax,
    boqs, emergencyContact, jurisdiction, ContactView,
    buildingByeLaws, HomeTemplateView, GalleryImageView, ForestView
)

from django.urls import path

app_name = "website"

# OFFICIAL
urlpatterns = [
    path('newsletter/create/', NewsLetterCreateView.as_view(), name='newsletter-create'),
]

# UN OFFICIAL
urlpatterns += [
    path('', HomeTemplateView.as_view(), name='home'),
    path('about/', about, name='about'),
    path('budget/', budget, name='budget'),
    path('contact-us/', ContactView.as_view(), name='contact_us'),
    path('forest-view/', ForestView.as_view(), name='forest'),
    # path('team/', team, name='team'),
    path('teamDetails/', teamDetails, name='teamDetails'),
    path('act/', act, name='gda_act'),
    path('department/', department, name='departments'),
    path('departmentDetails/', departmentDetails, name='department_details'),
    path('hotels/', hotels, name='hotels'),
    path('hotelsdetails/', hotelsDetails, name='hotels_details'),
    path('tenders/', tenders, name='tenders'),
    path('gallery/', GalleryImageView.as_view(), name='gallery'),
    path('cafe/', cafe, name='cafe'),
    path('cafedetail/', cafedetail, name='cafedetail'),
    path('watertax/', watertax, name='watertax'),
    path('conservancytax/', conservancytax, name='conservancytax'),
    path('propertytax/', TemplateView.as_view(template_name='website/property_tax.html'), name='propertytax'),
    path('boqs/', boqs, name='boqs'),
    path('emergency-contact/', emergencyContact, name='emergency_contact'),
    path('area-of-jurisdiction/', jurisdiction, name='jurisdiction'),
    path('building-bye-laws/', buildingByeLaws, name='building_bye_laws')
]

src/web/website/models.py
from django.db import models


class Visit(models.Model):
    count = models.IntegerField(default=0)

src/web/website/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView
from django.urls import reverse_lazy
from src.core.models import NewsLetter
from .models import Visit
from django.views.generic.edit import CreateView
from ...services.feedback.forms import ContactForm
from ...apps.weather.bll import get_galiyat_weather
from ...services.attractions.models import Attraction, AttractionArea
from ...services.departments.models import Directors, DirectorGeneral, Chairman
from ...services.dine_stay.models import Accommodation, Dining
from ...services.management.models import HomeSlider, GalleryImage

""" OFFICIAL """


class NewsLetterCreateView(View):

    def post(self, request):
        email = request.POST.get('email')

        # Check if email is provided
        if not email:
            messages.error(request, 'Please provide your email address.')
            return redirect(request.META.get('HTTP_REFERER'))

        # Check if email is already subscribed
        if NewsLetter.objects.filter(email=email).exists():
            messages.error(request, f"{email} you have already subscribed to our newsletter.")
            return redirect(request.META.get('HTTP_REFERER'))

        # Save email to database
        NewsLetter.objects.create(email=email)
        messages.success(request, 'You have successfully subscribed to our newsletter.')
        return redirect(request.META.get('HTTP_REFERER'))


""" UN-OFFICIAL """


def format_visit_count(count):
    if count < 1000:
        return str(count)
    elif count < 1000000:
        return f"{count // 1000}k"
    elif count < 1000000000:
        return f"{count // 1000000}M"
    else:
        return f"{count // 1000000000}B"


class HomeTemplateView(TemplateView):
    template_name = 'website/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['weather_data'] = get_galiyat_weather(self)
        context['top_attractions'] = AttractionArea.objects.all()[:10]
        context['restaurant'] = Accommodation.objects.all()[:10]
        context['dinning'] = Dining.objects.all()[:10]

        context['chairman'] = Chairman.objects.order_by('-created_at').first()
        context['director'] = Directors.objects.all()[:5]
        context['director_general'] = DirectorGeneral.objects.all()[:5]
        context['home_slider'] = HomeSlider.objects.all()

        visit_count = Visit.objects.first()

        if not visit_count:
            visit_count = Visit.objects.create(count=0)

        visit_count.count += 1
        visit_count.save()

        formatted_count = format_visit_count(visit_count.count)
        context['formatted_count'] = formatted_count
        return context


def about(request):
    return render(request, 'website/about.html')


def budget(request):
    return render(request, 'website/budget.html')


class ContactView(CreateView):
    template_name = 'website/contactUs.html'
    form_class = ContactForm
    success_url = reverse_lazy('website:contact_us')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Your message has been sent successfully!")
        return response


class ForestView(TemplateView):
    template_name = 'website/forest.html'


def team(request):
    return render(request, 'website/team.html')


def teamDetails(request):
    return render(request, 'website/teamDetails.html')


def act(request):
    return render(request, 'website/gda_act.html')


def department(request):
    return render(request, 'website/departments.html')


def departmentDetails(request):
    return render(request, 'website/departments_details.html')


def hotels(request):
    return render(request, 'website/hotels.html')


def hotelsDetails(request):
    return render(request, 'website/hotels_details.html')


def tenders(request):
    return render(request, 'website/tenders.html')


class GalleryImageView(ListView):
    model = GalleryImage
    template_name = 'website/gallery.html'
    context_object_name = 'images'


def cafe(request):
    return render(request, 'website/cafe.html')


def cafedetail(request):
    return render(request, 'website/cafedetail.html')


def watertax(request):
    return render(request, 'website/watertax.html')


def conservancytax(request):
    return render(request, 'website/conservancytax.html')


def boqs(request):
    return render(request, 'website/boqs.html')


def emergencyContact(request):
    return render(request, 'website/emergencyContact.html')


def jurisdiction(request):
    return render(request, 'website/jurisdiction.html')


def buildingByeLaws(request):
    return render(request, 'website/buildingbyelaws.html')

src/web/website/templates/website/include/footer.html
{% load static %}
{% load core_tags %}

<footer>
    <!--==================================================-->
    <!-- Startt Footer Area-->
    <!--==================================================-->
    <div class="footer-area">
        <div class="container">

            {# BANNER AREA #}
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-social-address">
                        <div class="row align-items-center">
                            <div class="col-lg-6 col-md-12">
                                <div class="footer-social-address-content">
                                    <h4>Stay with us On Social</h4>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12">
                                <div class="footer-social-icon">
                                    <ul>
                                        <li class="text">FOLOW US :</li>
                                        <li><a href=" {{ app.facebook }} "><i class="fab fa-facebook-f"></i></a></li>
                                        <li><a href="{{ app.twitter }}"><i class="fab fa-twitter"></i></a></li>
                                        <li><a href="{{ app.instagram }}"><i class="fab fa-instagram"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {# FULL FOOTER #}
            <div class="row add-footer-class">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-logo">
                        <a href="{% url 'website:home' %}">
                            
                            {% if app.logo %}
                                <img width="75px" src="{{ app.logo|image_or_placeholder:'70x70' }}" alt="logo">
                            {% else %}
                                <img src="{% static 'core/images/logos/logo.png' %}" alt="logo" width="250px">
                            {% endif %}
                        </a>
                    </div>
                    <p class="footer-desc">{{ app.tagline }}</p>
                    <div class="footer-contect-info">
                        <div class="footer-contact-info-title">
                            <h4>Contact</h4>
                        </div>
                        <ul>
                            <li><i class="bi bi-telephone-plus-fill"></i><a href="tel:{{app.contact_phone1}}" style="color:white;">{{app.contact_phone1}}</a></li>
                            <li><i class="bi bi-envelope-open-fill" ><p style="color:white;">{{app.contactemail1}} </p></i></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget-content">
                        <div class="footer-widget-title">
                            <h4>Quick Links</h4>
                        </div>
                        <div class="footer-widget-menu">
                            <ul>
                                <li><a href="{% url 'website:home' %}"><i class="fas fa-angle-right"></i>Home</a></li>
                                <li><a href="{% url 'website:about' %}"><i class="fas fa-angle-right"></i>About Us</a>
                                </li>
                                <li><a href="{% url 'website:contact_us' %}"><i class="fas fa-angle-right"></i>Contact
                                    Us</a></li>
                                     <li><a href="{% url 'website:gallery' %}"><i class="fas fa-angle-right"></i>Gallery</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget-content">
                        <div class="footer-widget-title">
                            <h4> More</h4>
                        </div>
                        <div class="footer-widget-menu">
                            <ul>
                                <li><a href="{% url 'departments:departments' %}"><i class="fas fa-angle-right"></i>Departments</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer-widget-content">
                        <div class="footer-widget-title">
                            <h4>Newsletter</h4>
                        </div>
                        <p>Subscribe our Newsletter</p>
                        <form action="{% url 'website:newsletter-create' %}" method="post">
                            <div class="single-newsletter-box">
                                {% csrf_token %}
                                <input type="text" id="email" name="email" placeholder="Your Email">
                                <button type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {# COPY RIGHT #}
        <div class="footer-bottom-area">
            <div class="container">
                <div class="row footer-bottom">
                    <div class="col-md-12 text-center">
                        <div class="footer-bottom-content">
                            <h4>
                                &copy; {% current_year %} All rights reserved <a href="/">Galiyat Development Authority</a>
                                deveoped by <a href="https://exarth.com/"><b>Exarth</b></a> under the super-vision of
                                <a href="#">Technical Director</a> of GDA.
                            </h4>                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End Footer Area-->
    <!--==================================================-->


    <!--==================================================-->
    <!-- End search-popup Area-->
    <!--==================================================-->
    <div class="search-popup">
        <button class="close-search style-two"><span class="flaticon-multiply"><i
                class="far fa-times-circle"></i></span></button>
        <button class="close-search"><i class="bi bi-arrow-up"></i></button>
        <form method="post" action="#">
            <div class="form-group">
                <input type="search" name="search-field" value="" placeholder="Search Here" required="">
                <button type="submit"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
    <!--==================================================-->
    <!-- End search-popup Area-->
    <!--==================================================-->


    <!--==================================================-->
    <!-- Start scrollup section Section -->
    <!--==================================================-->
    <div class="prgoress_indicator active-progress">
        <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
            <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"
                  style="transition: stroke-dashoffset 10ms linear 0s; stroke-dasharray: 307.919, 307.919; stroke-dashoffset: 0;"></path>
        </svg>
    </div>
    <!--==================================================-->
    <!-- End scrollup section Section -->
    <!--==================================================-->


</footer>

src/web/website/templates/website/include/header.html
{% load static %}
{% load core_tags %}
<header>
    
    <!--==================================================-->
    <!-- Start Top Header Area -->
    <!--==================================================-->

    <div class="top-header-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="top-header-info">
                        <ul>
                            <li><i class="bi bi-geo-alt"></i>{{ app.address }}</li>
                            <li><i class="bi bi-envelope-open"></i>{{ app.contact_email1 }}</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="top-header-right">
                        <div class="top-header-contact">
                            <span><i class="bi bi-telephone-fill"></i>{{ app.contact_phone1 }}</span>
                        </div>
                        <div class="top-header-social-icon">
                            <ul>
                                <li><a href="{{ app.facebook }}"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a href="{{ app.twitter }}"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="{{ app.instagram }}"><i class="fab fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End Top Header Area -->
    <!--==================================================-->


    <!--==================================================-->
    <!-- Start Header Area -->
    <!--==================================================-->
    
    <div class="header-area" id="sticky-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="header-logo">
                        <a href="/">
                            
                            {% if  app.logo %}
                            <img src="{{ app.logo.url }}" alt="logo" height="50">
                            {% else %}
                            <img src="{% static 'core/images/logos/logo.png' %}" alt="logo" height="50">
                            {% endif %}
                            </a>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="header-menu">
                        <ul>
                            <li class="menu-item-has-children"><a href="{% url 'website:home' %}">Home</i></a></li>

                            <li class="menu-item-has-children"><a href="#">Dine & Stay<i
                                    class="fas fa-chevron-down"></i></a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'dine_stay:accommodations' %}">Restaurants</a></li>
                                    <li><a href="{% url 'dine_stay:dinings' %}">Hotels and Cafes</a></li>
                                </ul>
                            </li>

                            
                            <li class="menu-item-has-children"><a href="/">Explore Galiyat<i class="fas fa-chevron-down"></i></a>
                                <ul class="sub-menu">
                                    <li>
                                        <li><a href="{% url 'attractions:attractions_list' %}">Attraction Points</a></li>
                                        <li><a href="{% url 'forest:wildlife_type' %}">Wild Life</a></li>
                                        <li><a href="{% url 'forest:greenery_type' %}">Greenery</a></li>
                                    </li>
                                </ul>
                            </li>                            
                            

                            <li class="menu-item-has-children"><a href="#">Tax Calculator<i
                                    class="fas fa-chevron-down"></i></a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'website:propertytax' %}">Property Taxes</a></li>
                                    <li><a href="{% url 'website:conservancytax' %}">Conservancy Taxes</a></li>
                                    <li><a href="{% url 'website:watertax' %}">Water Taxes</a></li>
                                </ul>
                            </li>

                            <li><a href="{% url 'events:event_list' %}">Events</a></li>
                            <li class="menu-item-has-children"><a href="#">More<i class="fas fa-chevron-down"></i></a>
                                <ul class="sub-menu">
                                    <li class="menu-item-has-children"><a href="{% url 'management:document-list' %}">Downloads</a></li>
                                    <li><a href="{% url 'website:gda_act' %}">GDA Act</a></li>
                                    <li><a href="{% url 'departments:gda_team' %}">Team</a></li>
                                    <li><a href="{% url 'departments:departments' %}">Departments</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mobile-menu-area sticky d-sm-block d-md-block d-lg-none ">
        <div class="mobile-menu">
            <nav class="header-menu">
                
                <ul class="nav_scroll">
                    <li class="menu-item-has-children"><a href="{% url 'website:home' %}">Home</i></a></li>

                    <li class="menu-item-has-children"><a href="#">Dine & Stay<i
                            class="fas fa-chevron-down"></i></a>
                        <ul class="sub-menu">
                            <li><a href="{% url 'dine_stay:accommodations' %}">Restaurants</a></li>
                            <li><a href="{% url 'dine_stay:dinings' %}">Hotels and Cafes</a></li>
                        </ul>
                    </li>

                    
                    <li class="menu-item-has-children"><a href="/">Explore Galiyat<i class="fas fa-chevron-down"></i></a>
                        <ul class="sub-menu">
                            <li>
                                <li><a href="{% url 'attractions:attractions_list' %}">Attraction Points</a></li>
                                <li><a href="{% url 'forest:wildlife_type' %}">Wild Life</a></li>
                                <li><a href="{% url 'forest:greenery_type' %}">Greenery</a></li>
                            </li>
                        </ul>
                    </li>                            
                    

                    <li class="menu-item-has-children"><a href="#">Tax Calculator<i
                            class="fas fa-chevron-down"></i></a>
                        <ul class="sub-menu">
                            <li><a href="{% url 'website:propertytax' %}">Property Taxes</a></li>
                            <li><a href="{% url 'website:conservancytax' %}">Conservancy Taxes</a></li>
                            <li><a href="{% url 'website:watertax' %}">Water Taxes</a></li>
                        </ul>
                    </li>

                    <li><a href="{% url 'events:event_list' %}">Events</a></li>
                    <li class="menu-item-has-children"><a href="#">More<i class="fas fa-chevron-down"></i></a>
                        <ul class="sub-menu">
                            <li class="menu-item-has-children"><a href="{% url 'management:document-list' %}">Downloads</a></li>
                            <li><a href="{% url 'website:gda_act' %}">GDA Act</a></li>
                            <li><a href="{% url 'departments:gda_team' %}">Team</a></li>
                            <li><a href="{% url 'departments:departments' %}">Departments</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>             
                  


    <!--==================================================-->
                    <!-- End Header Area -->
    <!--==================================================-->

</header>