core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from core.settings import ENVIRONMENT, MEDIA_ROOT, STATIC_ROOT
from src.core.handlers import (
    handler404, handler500
)

urlpatterns = []

""" HANDLERS ------------------------------------------------------------------------------------------------------- """
handler404 = handler404
handler500 = handler500

""" INTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('', include('src.web.urls')),
    path('', include('src.services.events.urls', namespace='events')),
    path('', include('src.services.departments.urls', namespace='departments')),
    path('', include('src.services.attractions.urls', namespace='attractions')),
    path('', include('src.services.dine_stay.urls', namespace='dine_stay')),
    path('', include('src.services.management.urls', namespace='management')),
    path('', include('src.services.forest.urls', namespace='forest')),
    path('', include('src.services.feedback.urls')),
    
    
]

""" EXTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/services/feedback/urls.py
urlpatterns = [
]

src/services/forest/urls.py
from django.urls import path
from .views import (
    WildlifeListView, WildlifeDetailView, WildlifeTypeListView,
    GreeneryListView, GreeneryDetailView, GreeneryTypeListView
)

app_name = 'forest'

urlpatterns = [
    # Wildlife URL patterns
    path('wildlife/types/', WildlifeTypeListView.as_view(), name='wildlife_type'),
    path('wildlife/list/<slug:slug>/', WildlifeListView.as_view(), name='wildlife_list'),
    path('wildlife/detail/<slug:slug>/', WildlifeDetailView.as_view(), name='wildlife_detail'),
    
    # Greenery URL patterns
    path('greenery/types/', GreeneryTypeListView.as_view(), name='greenery_type'),
    path('greenery/list/<slug:slug>/', GreeneryListView.as_view(), name='greenery_list'),
    path('greenery/detail/<slug:slug>/', GreeneryDetailView.as_view(), name='greenery_detail'),
]

src/web/website/urls.py
from django.views.generic import TemplateView

from .views import (

    NewsLetterCreateView,
    about, budget,
    teamDetails,
    act, department, departmentDetails,
    hotels, hotelsDetails, cafedetail,
    cafe, tenders,
    watertax,
    conservancytax,
    boqs, emergencyContact, jurisdiction, ContactView,
    watertax,
    conservancytax,
    boqs, emergencyContact, jurisdiction, ContactView,
    buildingByeLaws, HomeTemplateView, GalleryImageView, ForestView
)

from django.urls import path

app_name = "website"

# OFFICIAL
urlpatterns = [
    path('newsletter/create/', NewsLetterCreateView.as_view(), name='newsletter-create'),
]

# UN OFFICIAL
urlpatterns += [
    path('', HomeTemplateView.as_view(), name='home'),
    path('about/', about, name='about'),
    path('budget/', budget, name='budget'),
    path('contact-us/', ContactView.as_view(), name='contact_us'),
    path('forest-view/', ForestView.as_view(), name='forest'),
    # path('team/', team, name='team'),
    path('teamDetails/', teamDetails, name='teamDetails'),
    path('act/', act, name='gda_act'),
    path('department/', department, name='departments'),
    path('departmentDetails/', departmentDetails, name='department_details'),
    path('hotels/', hotels, name='hotels'),
    path('hotelsdetails/', hotelsDetails, name='hotels_details'),
    path('tenders/', tenders, name='tenders'),
    path('gallery/', GalleryImageView.as_view(), name='gallery'),
    path('cafe/', cafe, name='cafe'),
    path('cafedetail/', cafedetail, name='cafedetail'),
    path('watertax/', watertax, name='watertax'),
    path('conservancytax/', conservancytax, name='conservancytax'),
    path('propertytax/', TemplateView.as_view(template_name='website/property_tax.html'), name='propertytax'),
    path('boqs/', boqs, name='boqs'),
    path('emergency-contact/', emergencyContact, name='emergency_contact'),
    path('area-of-jurisdiction/', jurisdiction, name='jurisdiction'),
    path('building-bye-laws/', buildingByeLaws, name='building_bye_laws')
]

src/services/feedback/models.py
from django.db import models


class Contact(models.Model):
    SUBJECT_CHOICE = [
        ('restaurants', 'Restaurants'),
        ('tenders', 'Tenders'),
        ('technical', 'Technical'),
    ]

    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=20, choices=SUBJECT_CHOICE)
    message = models.TextField()

    def __str__(self):
        return self.name

src/web/website/models.py
from django.db import models


class Visit(models.Model):
    count = models.IntegerField(default=0)

src/services/feedback/forms.py
from django import forms

from src.services.feedback.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

        labels = {
            'name': 'Name',
            'email': 'Email',
            'subject': 'Subject',
            'message': 'Message',
        }

        placeholders = {
            'name': 'Enter Your Name*',
            'email': 'Enter Your Email*',
            'subject': 'Select Subject*',
            'message': 'Write Message',
        }

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': placeholders['name'],
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': placeholders['email'],
            }),
            'subject': forms.Select(choices=Contact.SUBJECT_CHOICE, attrs={
                'class': 'form-control',
                'placeholder': placeholders['subject'],
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': placeholders['message'],
            }),
        }

src/services/forest/views.py
from django.views.generic import ListView, DetailView
from .models import Greenery, Wildlife, WildlifeType, GreeneryType
from .filters import GreeneryFilter, GreeneryTypeFilter, WildLifeFilter, WildLifeTypeFilter
from django.core.paginator import Paginator


class WildlifeTypeListView(ListView):
    model = WildlifeType
    template_name = 'forest/wildlife_type.html'

    def get_queryset(self):
        return WildlifeType.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super(WildlifeTypeListView, self).get_context_data(**kwargs)
        _filter = WildLifeTypeFilter(self.request.GET, queryset=self.get_queryset())
        context['filter_form'] = _filter.form
        paginator = Paginator(_filter.qs, 20)
        page_number = self.request.GET.get('page')
        page_object = paginator.get_page(page_number)
        context['object_list'] = page_object
        return context


class WildlifeListView(ListView):
    model = Wildlife
    template_name = 'forest/wildlife.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return self.model.objects.filter(types__slug=self.kwargs['slug'], is_active=True)

    def get_context_data(self, **kwargs):
        
        context = super(WildlifeListView, self).get_context_data(**kwargs)
        _filter = WildLifeFilter(self.request.GET, queryset=self.get_queryset())
        context['filter_form'] = _filter.form
        paginator = Paginator(_filter.qs, 20)
        page_number = self.request.GET.get('page')
        page_object = paginator.get_page(page_number)
        context['object_list'] = page_object
        context['area_name'] = Wildlife.objects.filter(slug=self.kwargs.get('slug')).first()
        
        return context
    
    
class WildlifeDetailView(DetailView):
    model = Wildlife
    template_name = 'forest/wildlife_detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        
        context = super(WildlifeDetailView, self).get_context_data(**kwargs)
        context['attraction_category'] = WildlifeType.objects.all()[:15]
        context['more_hotels_and_cafe'] = Wildlife.objects.all()[:8]
        
        return context

    
class GreeneryTypeListView(ListView):
    model = GreeneryType
    template_name = 'forest/greenery_types.html'
    
    def get_queryset(self):
        return GreeneryType.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super(GreeneryTypeListView, self).get_context_data(**kwargs)
        _filter = GreeneryTypeFilter(self.request.GET, queryset=self.get_queryset())
        context['filter_form'] = _filter.form
        paginator = Paginator(_filter.qs, 20)
        page_number = self.request.GET.get('page')
        page_object = paginator.get_page(page_number)
        context['object_list'] = page_object
        return context


class GreeneryListView(ListView):
    model = Greenery
    template_name = 'forest/greenery_list.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return self.model.objects.filter(types__slug=self.kwargs['slug'], is_active=True)

    def get_context_data(self, **kwargs):
        context = super(GreeneryListView, self).get_context_data(**kwargs)
        _filter = GreeneryFilter(self.request.GET, queryset=self.get_queryset())
        context['filter_form'] = _filter.form
        paginator = Paginator(_filter.qs, 20)
        page_number = self.request.GET.get('page')
        page_object = paginator.get_page(page_number)
        context['object_list'] = page_object
        context['area_name'] = Greenery.objects.filter(slug=self.kwargs.get('slug')).first()
        return context
    
    
class GreeneryDetailView(DetailView):
    model = Greenery
    template_name = 'forest/greenery_detail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super(GreeneryDetailView, self).get_context_data(**kwargs)
        context['attraction_category'] = GreeneryType.objects.all()[:15]
        context['more_hotels_and_cafe'] = Wildlife.objects.all()[:8]
        return context

src/web/website/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView
from django.urls import reverse_lazy
from src.core.models import NewsLetter
from .models import Visit
from django.views.generic.edit import CreateView
from ...services.feedback.forms import ContactForm
from ...apps.weather.bll import get_galiyat_weather
from ...services.attractions.models import Attraction, AttractionArea
from ...services.departments.models import Directors, DirectorGeneral, Chairman
from ...services.dine_stay.models import Accommodation, Dining
from ...services.management.models import HomeSlider, GalleryImage

""" OFFICIAL """


class NewsLetterCreateView(View):

    def post(self, request):
        email = request.POST.get('email')

        # Check if email is provided
        if not email:
            messages.error(request, 'Please provide your email address.')
            return redirect(request.META.get('HTTP_REFERER'))

        # Check if email is already subscribed
        if NewsLetter.objects.filter(email=email).exists():
            messages.error(request, f"{email} you have already subscribed to our newsletter.")
            return redirect(request.META.get('HTTP_REFERER'))

        # Save email to database
        NewsLetter.objects.create(email=email)
        messages.success(request, 'You have successfully subscribed to our newsletter.')
        return redirect(request.META.get('HTTP_REFERER'))


""" UN-OFFICIAL """


def format_visit_count(count):
    if count < 1000:
        return str(count)
    elif count < 1000000:
        return f"{count // 1000}k"
    elif count < 1000000000:
        return f"{count // 1000000}M"
    else:
        return f"{count // 1000000000}B"


class HomeTemplateView(TemplateView):
    template_name = 'website/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['weather_data'] = get_galiyat_weather(self)
        context['top_attractions'] = AttractionArea.objects.all()[:10]
        context['restaurant'] = Accommodation.objects.all()[:10]
        context['dinning'] = Dining.objects.all()[:10]

        context['chairman'] = Chairman.objects.order_by('-created_at').first()
        context['director'] = Directors.objects.all()[:5]
        context['director_general'] = DirectorGeneral.objects.all()[:5]
        context['home_slider'] = HomeSlider.objects.all()

        visit_count = Visit.objects.first()

        if not visit_count:
            visit_count = Visit.objects.create(count=0)

        visit_count.count += 1
        visit_count.save()

        formatted_count = format_visit_count(visit_count.count)
        context['formatted_count'] = formatted_count
        return context


def about(request):
    return render(request, 'website/about.html')


def budget(request):
    return render(request, 'website/budget.html')


class ContactView(CreateView):
    template_name = 'website/contactUs.html'
    form_class = ContactForm
    success_url = reverse_lazy('website:contact_us')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Your message has been sent successfully!")
        return response


class ForestView(TemplateView):
    template_name = 'website/forest.html'


def team(request):
    return render(request, 'website/team.html')


def teamDetails(request):
    return render(request, 'website/teamDetails.html')


def act(request):
    return render(request, 'website/gda_act.html')


def department(request):
    return render(request, 'website/departments.html')


def departmentDetails(request):
    return render(request, 'website/departments_details.html')


def hotels(request):
    return render(request, 'website/hotels.html')


def hotelsDetails(request):
    return render(request, 'website/hotels_details.html')


def tenders(request):
    return render(request, 'website/tenders.html')


class GalleryImageView(ListView):
    model = GalleryImage
    template_name = 'website/gallery.html'
    context_object_name = 'images'


def cafe(request):
    return render(request, 'website/cafe.html')


def cafedetail(request):
    return render(request, 'website/cafedetail.html')


def watertax(request):
    return render(request, 'website/watertax.html')


def conservancytax(request):
    return render(request, 'website/conservancytax.html')


def boqs(request):
    return render(request, 'website/boqs.html')


def emergencyContact(request):
    return render(request, 'website/emergencyContact.html')


def jurisdiction(request):
    return render(request, 'website/jurisdiction.html')


def buildingByeLaws(request):
    return render(request, 'website/buildingbyelaws.html')

src/web/website/templates/website/about.html
{% extends 'website/base.html' %}

{% load static %}

{% block title %} About us {% endblock title %}

{% block style %}
    h4 {
      text-align: center;
      margin-top: 20px;
      margin-bottom: 20px;
    }
    .responsibility-item {
      margin-bottom: 20px;
    }

{% endblock style %}
    

{% block content %}


    <!--==================================================-->
    <!-- Start Breadcumb Area -->
    <!--==================================================-->
    <div class="breadcumb-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 text-center">
                    <div class="breadcumb-content">
                        <div class="breadcumb-title">
                            <h4>About Us</h4>
                        </div>
                        <ul>
                            <li><a href="{% url 'website:home' %}"><img
                                    src="{% static 'website/images/inner-images/breadcumb-text-shape.png' %}" alt="">GDA
                                - </a></li>
                            <li>About Us</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End Breadcumb Area -->
    <!--==================================================-->



    <!--==================================================-->
    <!-- Strat About Area -->
    <!--==================================================-->
    <div class="about-area home-two">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-12">
                    <div class="about-thumb">
                        <img height=600px src="{% static 'website/images/home2/galiyat-map.jpg' %}" width="650px"
                             alt="">
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="about-right">
                        <div class="section-title left">
                            <h4><img src="{% static 'website/images/home1/section-shape.png' %}" alt="">Get to know GDA
                            </h4>
                            <h1>Galiyat Development Authority</h1>
                        </div>
                        <div class="about-text">
                            <span><img src="{% static 'website/images/home2/shape.png' %}" alt=""></span><a href=" {% url 'departments:departments' %} ">We’ve
                            been serving Galiyat for the past 10+ years</a>
                        </div>

                        <p class="about-desc">The Galiyat Development Authority was established on 8th June 1999 as a
                            succession body of Hazara Hill Tract Improvement Trust under GDA act of 1996.</p>
                        <p class="about-desc">In 1961 under an ordinance promulgated by the then government of West
                            Pakistan vide law department notification No: Log.3 (8)/61 dated: 22-04-1961, the Rawalpindi
                            & Hazara Hill tract Improvement Trust was created and assigned the responsibility to develop
                            the abandoned Cantt: of Ghoradhakka, Khanspur, Changla Gali and Khaira Gali into hill
                            resorts. Ayubia comprising of three townships viz. Ghoradhakka / Khanspur Changla Gali and
                            Khaira Gali were taken over by the Trust for its development in 1962/63. The notified area
                            committee of Nathiagali handed over the administrative control of Nathiagali and Donga Gali
                            in the year 1970. Later on the Provincial Govt. transferred the Thandiani Township to the
                            Galiyat Development Authority as well. Creation of GDA The Galiyat Development Authority was
                            established on 8th June 1999 as a succession body of Hazara Hill Tract Improvement Trust
                            under GDA act of 1996.</p>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                      <div class="col-12">
                        <h4>Our Responsibilities</h4>
                        <ul class="list-group">
                          <li class="list-group-item responsibility-item">
                            <h6>SUPPLY OF WATER</h6>
                            <p>Water supply is being ensured to the stakeholders i.e. Plot owners, Shopkeepers with nominal charges. Water is being streamlined to water tanks from different streams located at Galiyat and distributed through pumping to the tanks located at Nathiagali, Ayubia, etc.</p>
                          </li>
                          <li class="list-group-item responsibility-item">
                            <h6>SANITATION</h6>
                            <p>GDA has sufficient sanitation staff at Galiyat for sanitation and cleanliness of the main and town roads. GDA has three compactors for garbage collection and disposal. Cleanliness campaigns are regularly run by GDA to raise awareness among the general public and visitors. GDA actively participates in the Govt. of Pakistan manifesto of “Clean and Green Pakistan”.</p>
                          </li>
                          <li class="list-group-item responsibility-item">
                            <h6>BEAUTIFICATION OF GALIYAT</h6>
                            <p>A comprehensive project has been completed for the beautification of Galiyat. The purpose of the project was the uplifting of Galiyat. Five rest areas were established along the highway with male and female washrooms and a flower market was established at Nathiagali.</p>
                          </li>
                          <li class="list-group-item responsibility-item">
                            <h6>STREET LIGHTS</h6>
                            <p>Street lights were installed in the Galiyat region from Nathiagali to Ayubia as part of the “Beautification of Galiyat” project.</p>
                          </li>
                          <li class="list-group-item responsibility-item">
                            <h6>COMPLAINT CELL</h6>
                            <p>An online Complaint Cell has been established in GDA to hear grievances from the general public. GDA takes immediate steps to resolve grievances. Mostly, complaints regarding encroachments, street lights, sanitation, water supply, rest houses, and snow/slide clearance are received and addressed.</p>
                          </li>
                          <li class="list-group-item responsibility-item">
                            <h6>CONTROL ROOM FOR SNOW / SLIDE CLEARANCE</h6>
                            <p>During the snowfall season, a 24/7 control room is established for information dissemination regarding weather conditions, road situations, rescue, and snow/slide clearance. The Control Room of GDA remains in close liaison with the District Government, field staff, media, and contractors. During snow, GDA works in collaboration with KPHA and the C & W department.</p>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End About Area -->
    <!--==================================================-->



    <!--==================================================-->
    <!-- Strat Counter Area -->
    <!--==================================================-->
    <div class="area mb-4">
        <div class="container mb-4">
            <div class="row mb-4">
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="card"> <!-- Updated ID -->
                        <div class="card-header">
                            <h4>
                                Conduct of Business
                            </h4>
                        </div>
                        <div class="p-4">
                            According to the GDA act 1996 the affairs of the Authority is governed by the Board
                            of Authority.
                            Chapter I & II of the act relates to constitution and establishment of the Authority
                            and Chapter III relates to power and function of the Authority as well chapter IV
                            and V relates to the appointment of DG and his executive powers to conduct the daily
                            business of the authority.
                            GDA building Bye-laws were approved by District Government Abbottabad during 2003.
                            Later on, in a meeting of the board of authority held on 14-05-2007, a committee
                            under the supervision of Secretary Local Govt: was constituted to reframe and amend
                            the GDA bye-laws and preparation of Bye-Laws are near completion which will very
                            shortly be placed before the committee.
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="card"> <!-- Updated ID -->
                        <div class="card-header">
                            <h4>
                                Function
                            </h4>
                        </div>
                        <div class="p-4">
                            The basic aim to establish the authority was to provide infrastructural and civic facilities
                            such as water supply draining waste management, roads, street lights, parking and
                            development of parks in the entire Galiyat townships beside planning/zoning of an unplanned
                            area into new resorts/township schemes.
                            To levy and collect taxes.
                            To sell, lease, exchange or dispose of any property vested in it.
                            To exercise and control building regulation through BCA and building bye-laws.
                            Tourism infrastructure development.
                            To undertake any other functions which the provincial government may assign to it.
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-sm-6 col-12">
                    <div class="card"> <!-- Updated ID -->
                        <div class="card-header">
                            <h4>
                                Present Status
                            </h4>
                        </div>
                        <div class="p-4">
                            Upon the devolution plan, while pending the repeal of GDA act. The GDA was devolved under
                            the District Government. But in September 2004 vide a notification bearing no.
                            AO-LG/LCB/5-58/2004, dated 21.09.2004 the provincial government reconstituted the GDA as
                            Provincial Autonomous body/entity.
                            Later on, the limits/sphere of activities of GDA has extended by provincial Government vide
                            Notification No. C/SADC/PEND/31/2000 dated 30.03.2000 to the extent of Qanoongo Circle Lora,
                            Bagan and Bekot.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End Counter Area -->
    <!--==================================================-->


{% endblock content %}

src/web/website/templates/website/forest.html
{% extends 'website/base.html' %}
{% load core_tags %}
{% load static %}

{% block title %} Forest {% endblock title %}

{% block style %}

{% endblock style %}

{% block content %}

    {# BACKGROUND BANNER FOREST #}
    <div class="breadcumb-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 text-center">
                    <div class="breadcumb-content">
                        <div class="breadcumb-title">
                            <h4>FORESTORY</h4>
                        </div>
                        <ul>
                            <li><a href="{% url 'website:home' %}"><img
                                    src="assets/images/inner-images/breadcumb-text-shape.png" alt="">GDA</a></li>
                            <li>Forest</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {# SELECT YOUR CHOICE #}
    <div class="service-area home-two inner">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-title center">
                        <h1>GDA Provides a Flourishing Environment</h1>
                        <p>Experience the beauty of wildlife and greenery with GDA, where nature's wonders come alive
                            in perfect harmony.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-12">
                    <a href="{% url 'forest:wildlife_list' %}">
                        <div class="single-service-box">
                            <div class="service-thumb">
                                <img src="{% static 'website/images/home2/services-1.png' %}" alt="">
                            </div>
                            <div class="service-content">
                                <a href="{% url 'forest:wildlife_list' %}">Wild Life</a>
                                <p>Pioneering efforts to protect wildlife and preserve their natural habitats.</p>
                                <div class="service-button">
                                    <a href="{% url 'forest:wildlife_list' %}">Discover More<i
                                            class="bi bi-arrow-right-short"></i></a>
                                </div>
                            </div>
                        </div>
                    </a>

                </div>

                <div class="col-lg-6 col-md-12">
                    <a href="{% url 'forest:greenery_list' %}">
                        <div class="single-service-box">
                            <div class="service-thumb">
                                <img src="{% static 'website/images/home2/services-1.png' %}" alt="">
                            </div>
                            <div class="service-content">
                                <a href="{% url 'forest:greenery_list' %}">Greenery</a>
                                <p>Promoting greenery & sustainable landscapes for a healthier planet.</p>
                                <div class="service-button">
                                    <a href="{% url 'forest:greenery_list' %}">Discover More<i
                                            class="bi bi-arrow-right-short"></i></a>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>

            </div>
        </div>
    </div>


{% endblock content %}