core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from core.settings import ENVIRONMENT, MEDIA_ROOT, STATIC_ROOT
from src.core.handlers import (
    handler404, handler500
)

urlpatterns = []

""" HANDLERS ------------------------------------------------------------------------------------------------------- """
handler404 = handler404
handler500 = handler500

""" INTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('', include('src.web.urls')),
    path('', include('src.services.events.urls', namespace='events')),
    path('', include('src.services.departments.urls', namespace='departments')),
    path('', include('src.services.attractions.urls', namespace='attractions')),
    path('', include('src.services.dine_stay.urls', namespace='dine_stay')),
    path('', include('src.services.management.urls', namespace='management')),
    path('', include('src.services.forest.urls', namespace='forest')),
    path('', include('src.services.feedback.urls')),
    
    
]

""" EXTERNAL REQUIRED APPS ----------------------------------------------------------------------------------------- """
urlpatterns += [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]

""" DEVELOPMENT ONLY -------------------------------------------------------------------------------------------- """
if ENVIRONMENT != 'server':
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls"))
    ]

src/services/events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView

app_name = 'events'
urlpatterns = [
    path('event/list/', EventListView.as_view(), name='event_list'),
    path('event/<str:slug>/detail', EventDetailView.as_view(), name='event_detail')
]

src/web/website/urls.py
from django.views.generic import TemplateView

from .views import (

    NewsLetterCreateView,
    about, budget,
    teamDetails,
    act, department, departmentDetails,
    hotels, hotelsDetails, cafedetail,
    cafe, tenders,
    watertax,
    conservancytax,
    boqs, emergencyContact, jurisdiction, ContactView,
    watertax,
    conservancytax,
    boqs, emergencyContact, jurisdiction, ContactView,
    buildingByeLaws, HomeTemplateView, GalleryImageView, ForestView
)

from django.urls import path

app_name = "website"

# OFFICIAL
urlpatterns = [
    path('newsletter/create/', NewsLetterCreateView.as_view(), name='newsletter-create'),
]

# UN OFFICIAL
urlpatterns += [
    path('', HomeTemplateView.as_view(), name='home'),
    path('about/', about, name='about'),
    path('budget/', budget, name='budget'),
    path('contact-us/', ContactView.as_view(), name='contact_us'),
    path('forest-view/', ForestView.as_view(), name='forest'),
    # path('team/', team, name='team'),
    path('teamDetails/', teamDetails, name='teamDetails'),
    path('act/', act, name='gda_act'),
    path('department/', department, name='departments'),
    path('departmentDetails/', departmentDetails, name='department_details'),
    path('hotels/', hotels, name='hotels'),
    path('hotelsdetails/', hotelsDetails, name='hotels_details'),
    path('tenders/', tenders, name='tenders'),
    path('gallery/', GalleryImageView.as_view(), name='gallery'),
    path('cafe/', cafe, name='cafe'),
    path('cafedetail/', cafedetail, name='cafedetail'),
    path('watertax/', watertax, name='watertax'),
    path('conservancytax/', conservancytax, name='conservancytax'),
    path('propertytax/', TemplateView.as_view(template_name='website/property_tax.html'), name='propertytax'),
    path('boqs/', boqs, name='boqs'),
    path('emergency-contact/', emergencyContact, name='emergency_contact'),
    path('area-of-jurisdiction/', jurisdiction, name='jurisdiction'),
    path('building-bye-laws/', buildingByeLaws, name='building_bye_laws')
]

src/services/events/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from django_resized import ResizedImageField
from phonenumber_field.modelfields import PhoneNumberField


class EventType(models.Model):
    name = models.CharField(max_length=100)
    image = ResizedImageField(
        size=[500, 500], quality=100, upload_to='events/event-type/images', blank=True, null=True
    )
    description = models.TextField(blank=True, null=True)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Event Type'
        verbose_name_plural = 'Event Types'

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        self.image.delete(save=True)
        super(EventType, self).delete(*args, **kwargs)


class Event(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    event_type = models.ForeignKey(EventType, on_delete=models.CASCADE)

    thumbnail = ResizedImageField(
        size=[500, 500], quality=75, upload_to='events/event/images', blank=True, null=True,
        help_text='size of logo must be 500*500 and format must be png image file'
    )
    banner = ResizedImageField(
        quality=75, upload_to='events/event/images', blank=True, null=True,
        help_text='size of logo must be banner size and format must be png image file'
    )

    description = models.TextField(blank=True, null=True)
    content = CKEditor5Field('Text', config_name='extends', null=True, blank=True)

    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    location = models.TextField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Event'
        verbose_name_plural = 'Events'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = self.name.replace(' ', '-').lower()
        super(Event, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.thumbnail.delete(save=True)
        self.banner.delete(save=True)
        super(Event, self).delete(*args, **kwargs)


class EventImage(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    image = ResizedImageField(
        size=[800, 800], quality=100, upload_to='events/event/images', blank=True, null=True,
        help_text='size of logo must be 800*800 and format must be png image file'
    )

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Event Image'
        verbose_name_plural = 'Event Images'

    def __str__(self):
        return self.event.name

    def delete(self, *args, **kwargs):
        self.image.delete(save=True)
        super(EventImage, self).delete(*args, **kwargs)


class Participant(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = PhoneNumberField(blank=True, null=True, )
    address = models.TextField(blank=True, null=True)

    user = models.ForeignKey('users.User', on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Participant'
        verbose_name_plural = 'Participants'

    def __str__(self):
        return f'{self.user.email} - {self.event.name}'


class Guest(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField(null=True,blank=True)
    phone_number = PhoneNumberField(blank=True, null=True, )
    designation = models.CharField(max_length=100, blank=True, null=True)
    image = ResizedImageField(
        size=[500, 500], quality=100, upload_to='events/guest/images', blank=True, null=True,
        help_text='size of logo must be 500*500 and format must be png image file'
    )

    event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True, null=True)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Guest'
        verbose_name_plural = 'Guests'

    def __str__(self):
        return self.full_name

    def delete(self, *args, **kwargs):
        self.image.delete(save=True)
        super(Guest, self).delete(*args, **kwargs)

src/services/events/views.py
from .models import Event, EventType
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from .filters import EventFilter


class EventListView(ListView):
    model = Event
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        _filter = EventFilter(self.request.GET, queryset=self.get_queryset())
        context['filter_form'] = _filter.form
        paginator = Paginator(_filter.qs, 10)
        page_number = self.request.GET.get('page')
        page_object = paginator.get_page(page_number)
        context['object_list'] = page_object
        return context


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/eventdetail.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        context['event_type'] = EventType.objects.all()[:5]
        context['latest_events'] = Event.objects.order_by("-created_at")[:5]
        return context

src/services/events/templates/events/eventdetail.html
{% extends 'website/base.html' %}
{% load core_tags %}
{% load static %}

{% block title %}
    {{ object.name }}
{% endblock title %}


{% block style %}



{% endblock style %}


{% block content %}

    <!--==================================================-->
    <!-- Start Breadcumb Area -->
    <!--==================================================-->
    <div class="breadcumb-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 text-center">
                    <div class="breadcumb-content">
                        <div class="breadcumb-title">
                            <span><img src="{{ object.thumbnail|image_or_placeholder }}" alt=""></span>
                            <h4>{{ object.name }}</h4>
                        </div>
                        <ul>
                            <li><a href="#"><img
                                    src="{% static 'website/images/inner-images/breadcumb-text-shape.png' %}" alt="">Galiyat</a>
                            </li>
                            <li>{{ object.name }} Details</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End Breadcumb Area -->
    <!--==================================================-->

    <section class="event-details-section">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="blog-details-content">
                                <div class="meta-blog">
                                </div>
                                <p class="blog-details-desc">{{ object.description }}</p>
                                <p class="blog-details-desc">{{ object.content|safe }}</p>
                                       <h3 class="text-success mt-4 text-center">Our Guests</h3>
                                <div class="row">
                                    {% if object.guest_set.all %}
                                        {% for guest in object.guest_set.all %}
                                            <div class="col-lg-4 col-md-6">
                                                <div class="single-team-box">
                                                    <div class="single-team-thumb">
                                                        <img src="{{ guest.image|image_or_placeholder }}" alt="">
                                                    </div>
                                                    <div class="team-content">
                                                        <h4>{{guest.full_name}}</h4>
                                                        <p>{{guest.designation}}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    {% else %}
                                        <div class="col-lg-4 col-md-6">
                                        <b class="text-danger text-center">Guest Not Added yet</b>
                                        </div>
                                    {% endif %}
                                </div>
                                <div style="width: 100%">
                                    <iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0"
                                            marginwidth="0"
                                            src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q={{ object.latitude }},{{ object.longitude }}+(My%20Business%20Name)&amp;t=k&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed">
                                        <a href="https://www.gps.ie/"></a>
                                    </iframe>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="widget-sidber">
                                <div class="widget_search">
                                    <form action="{% url 'events:event_list' %}"
                                          method="get">
                                        <input type="text" name="name" value="" placeholder="Search Here"
                                               title="Search for:">
                                        <button type="submit" class="icons">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="widget-sidber">
                                <div class="widget-sidber-content">
                                    <h4>Categories</h4>
                                </div>
                                <div class="widget-category">
                                    <ul>
                                        {% for category in event_type %}
                                            <li>
                                                <a href="{% url 'events:event_list' %}?event_type={{ category.id }}"><img
                                                        src="{% static 'website/images/inner-images/category-icon.png' %}"
                                                        alt="">{{ category.name }}<i class="bi bi-arrow-right"></i></a>
                                            </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                            </div>
                            <div class="widget-sidber">
                                <div class="widget-sidber-content">
                                    <h4>Latest Events</h4>
                                </div>

                                {% for attraction in latest_events %}
                                    <div class="sidber-widget-recent-post">
                                        <div class="recent-widget-thumb">
                                            <img src="{{ attraction.thumbnail|image_or_placeholder }}"
                                                 style="height: 50px" alt="">
                                        </div>
                                        <div class="recent-widget-content">
                                            <a href="{% url 'events:event_detail' attraction.slug %}">{{ attraction.name }}</a>
                                            <p class="text-secondary">{{ attraction.description|slice:60 }} .....</p>
                                            <p> {{ attraction.created_at.date }}</p>
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-title center">
                    <h4><img src="{% static 'website/images/home1/section-shape.png' %}" alt="">Images</h4>
                    <h1>Images of {{ object }}</h1>
                </div>
            </div>
        </div>
        <div class="row mb-4">
            <div class="project-list-2 owl-carousel mb-4">
                {% if  object.eventimage_set %}
                    {% for image in object.eventimage_set.all %}

                        <div class="col-lg-12 mb-4">
                            <div class="single-project-box">
                                <div class="project-thumb">
                                    <img src="{{ image.image|image_or_placeholder }}" alt="">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                <div class="mt-50 mb-100 ml-sm-0 ml-md-200">
                    <h3 class="text-danger">Image unavailable</h3>
                </div>
                
                {% endif %}

            </div>
        </div>
    </div>

        <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Function to remove the disabled class from navigation buttons and dots
            function removeDisabled() {
                var disabledElements = document.querySelectorAll(' .owl-dots.disabled');
                disabledElements.forEach(function (element) {
                    element.classList.remove('disabled');
                });
            }

            var owlDots = document.querySelectorAll('.owl-dots');

            // Loop through each element with the class "owl-dots"
            owlDots.forEach(function (dot) {
                // Remove the "disabled" class
                dot.classList.remove('disabled');

                // Add click event listener to each dot
                dot.addEventListener('click', function () {
                    // Remove the "disabled" class when a dot is clicked
                    dot.classList.remove('disabled');
                });
            });

            // Call the function initially
            removeDisabled();

            // Check for and remove the disabled class every 5 seconds
            setInterval(removeDisabled, 1); // 5000 milliseconds = 5 seconds
        });

    </script>


{% endblock content %}
    

src/services/events/templates/events/events.html
{% extends 'website/base.html' %}
{% load crispy_forms_filters %}
{% load core_tags %}
{% load static %}
{% load widget_tweaks %}


{% block title %} Events {% endblock title %}

{% block content %}

    <!--==================================================-->
    <!-- Start Breadcumb Area -->
    <!--==================================================-->
    <div class="breadcumb-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 text-center">
                    <div class="breadcumb-content">
                        <div class="breadcumb-title">
                            <img src="{{ area_name.image|image_or_placeholder }}"
                                 style="height: 100px;border-radius: 30px" class="img-rounded">
                            <h4>{{ area_name }}</h4>
                            <p class="text-white">{{ area_name.detail }}</p>
                        </div>
                        <ul>
                            <li><a href="{% url 'website:home' %}"><img
                                    src="{% static 'website/images/inner-images/breadcumb-text-shape.png' %}" alt="">Galiyat</a>
                            </li>
                            <li>{{ area_name }} Event</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--==================================================-->
    <!-- End Breadcumb Area -->
    <!--==================================================-->


    <section class="feature-five mt-5 mb-5">
        <div class="container">

            <div class="row">

                <div class="col-md-12">
                    <form method="get">
                        <div class="row ">
                            <div class="input-group mb-3">
                                {% render_field filter_form.name class="form-control" placeholder='Nathia Gali Church Park ' %}
                                <small class="filter_form-text text-muted">{{ filter_form.name.help_text }}</small>
                                {% if filter_form.name.errors %}
                                    <ul class="text-danger">
                                        {% for error in filter_form.name.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}

                                {% render_field filter_form.event_type class="form-control" placeholder='Galiyat Snow Festival ' %}
                                <small class="filter_form-text text-muted">{{ filter_form.event_type.help_text }}</small>
                                {% if filter_form.event_type.errors %}
                                    <ul class="text-danger">
                                        {% for error in filter_form.event_type.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                                <div class="input-group-append">
                                    <button class="btn btn-outline-success btn-lg" type="submit"><i
                                            class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>

                        </div>
                    </form>

                </div>

            </div>

        <div class="home-six">
            <div class="container">
                  <div class="row" id="events_list">

                {% if object_list %}
                    {% for object in object_list %}
                                <div class="col-lg-4 col-md-6 mb-4  card-length">
                            <div class="single-blog-box">
                                <div class="blog-thumb">
                                    {% if object.thumbnail %}
                                        <img src="{{ object.thumbnail|image_or_placeholder }}" alt="">
                                    {% else %}
                                        <img src="https://placehold.co/200" alt="">
                                    {% endif %}
                                </div>
                                <div class="blog-content">
                                    <div class="blog-text">
                                        <span>{{ object.created_at }}</span>
                                    </div>
                                    <a href="{% url 'events:event_detail' object.slug %}">{{ object.name }}</a>
                                    <p>{{ object.description|slice:100 }}...</p>

                                    <div class="blog-button">
                                        <a href="{% url 'events:event_detail' object.slug %}">Explore
                                            More<i class="bi bi-arrow-right-short"></i></a>
                                    </div>
                                </div>
                                <div class="meta-blog">
                                    <span>{{ object.created_at.date }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                {% else %}

                <div class="mt-50 mb-100 ml-sm-0 ml-md-200">
                    <h3 class="text-danger">Apologies, Events are Currently Unavailable</h3>
                </div>
                
                
                {% endif %}


            </div>
            <nav class="custome-pagination">
                <ul class="pagination justify-content-center">
                    {% if object_list.has_next %}
                        <li class="page-item">
                            <button id="load-more-btn" class="btn btn-success btn-md text-white mt-4">Load More
                            </button>
                            <div class="align-items-center mb-4 mt-3 mt-sm-0" id="loading-spinner"
                                 style="display:none;">

                                <div class="spinner-grow text-success" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                <div class="spinner-grow text-success" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                <div class="spinner-grow text-success" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                <div class="spinner-grow text-success" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                <div class="spinner-grow text-success" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                                <div class="spinner-grow text-success" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>

                            </div>

                        </li>
                    {% endif %}
                </ul>
            </nav>
            <div class="row align-items-center mb-4 text-center text-sm-start" id="pagination-element">
                <div class="col-sm-5">
                    <div class="text-muted" id="pagination-info">
                        Showing {{ object_list.start_index }} to {{ object_list.end_index }}
                        of {{ object_list.paginator.count }} entries
                    </div>
                </div>
            </div>
            </div>
        </div>

        </div>
    </section>

{% endblock content %}

{% block internal-js %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $("#id_event_type option:first").text("Select Event Type");

            var page = {% if object_list.has_next %}{{ object_list.next_page_number }}{% else %}null{% endif %};
            var maxPages = {{ object_list.paginator.num_pages }};
            var loading = false;

            function loadMore() {
                if (loading || page === null || page > maxPages) {
                    return;
                }
                loading = true;
                $('#load-more-btn').hide();
                $('#loading-spinner').show();
                var searchQuery = window.location.search;

                var filter_queryset = null
                if (searchQuery) {
                    filter_queryset = searchQuery + '&page=' + page
                } else {
                    filter_queryset = '?page=' + page
                }

                $.ajax({
                    url: filter_queryset,
                    type: 'GET',
                    dataType: 'html',
                    success: function (data) {
                        var $data = $(data);
                        var $shopList = $data.find('#events_list');

                        if ($shopList.find('.card-length').length > 0) {
                            $('#events_list').append($shopList.html());
                            $('#loading-spinner').hide();
                            $('#load-more-btn').show();
                            page++;
                            loading = false;

                            updatePaginationInfo();
                        } else {
                            $('#loading-spinner').hide();
                            $('#load-more-btn').hide();
                        }
                    },
                    error: function () {
                        loading = false;
                    }
                });
            }

            function updatePaginationInfo() {
                $('#pagination-info').text('Showing 1 to ' + $('#events_list .card-length').length + ' of {{ object_list.paginator.count }} entries');

                if (page === null || page > maxPages) {
                    $('#load-more-btn').hide();
                }
            }

            if (page === null || page > maxPages) {
                $('#load-more-btn').hide();
            }

            $('#load-more-btn').on('click', loadMore);
        });
    </script>
{% endblock %}